import { ThemeObjectType } from "src/app/core/types/general";

export const MONTHS = [
    { name: "january", order: 0, short: "jan" },
    { name: "february", order: 1, short: "feb" },
    { name: "march", order: 2, short: "mar" },
    { name: "april", order: 3, short: "apr" },
    { name: "may", order: 4, short: "may" },
    { name: "june", order: 5, short: "jun" },
    { name: "july", order: 6, short: "jul" },
    { name: "august", order: 7, short: "aug" },
    { name: "september", order: 8, short: "sep" },
    { name: "october", order: 9, short: "out" },
    { name: "november", order: 10, short: "nov" },
    { name: "december", order: 11, short: "dec" },
];

export const WEEKDAYS = [
    { name: "sunday", order: 0, short: "sun" },
    { name: "monday", order: 1, short: "mon" },
    { name: "tuesday", order: 2, short: "tue" },
    { name: "wednesday", order: 3, short: "wed" },
    { name: "thursday", order: 4, short: "thu" },
    { name: "friday", order: 5, short: "fri" },
    { name: "saturday", order: 6, short: "sat" },
];

export const THEMES: ThemeObjectType[] = [
    {
        title: "default",
        id: "default",
        description: "the default theme of the application",
        "--primary": "#4cafc4",
        "--secondary": "#da8cc1",
        "--third": "#cd7667",
        "--background": "#f4fafb",
        "--bh": "rgb(from var(--background) calc(r - 10) calc(g - 10) calc(b - 10))",
        "--text-1": "#000d55",
        "--text-2": "#3c3e5c",
        "--text-3": "#d5d6f1",
        "--border-color": "#4cafc4",
        "--disabled": "#7a7a7a67",
        "--error": "#bb3232",
        "--warning": "#b9882d",
        "--info": "#0b3d9b",
        "--success": "#248133",
        "--default": "#474141",
        "--credit-card": "#da3434",
        "--bank": "#5c84da",
        "--company": "#a369d3",
        "--category": "#44acac",
        "--bill": "#ac9d44",
    },
    {
        title: "dark violet",
        id: "dark",
        description: "the dark theme of the application",
        "--primary": "#878cec",
        "--secondary": "#4f1790",
        "--third": "#8c2bdd",
        "--background": "#030311",
        "--bh": "rgb(from var(--background) calc(r + 10) calc(g + 10) calc(b + 20))",
        "--text-1": "#d5d6f1",
        "--text-2": "#5e6192ff",
        "--text-3": "#000d55",
        "--border-color": "#878cec",
        "--disabled": "#7a7a7a67",
        "--error": "#bd5252",
        "--warning": "#ca8215",
        "--info": "#1346b4",
        "--success": "#0d8844",
        "--default": "#474141",
        "--credit-card": "#a73f3f",
        "--bank": "#1346b4",
        "--company": "#622991",
        "--category": "#2a8a8a",
        "--bill": "#ac9d44",
    },
    {
        title: "black and white",
        id: "binary",
        description:
            "the full dark theme of the application, with only black and color lines",
        "--primary": "#000000",
        "--secondary": "#ffffff",
        "--third": "#000000",
        "--background": "#000000",
        "--bh": "#000000",
        "--text-1": "#ffffff",
        "--text-2": "#ffffff",
        "--text-3": "#ffffff",
        "--border-color": "#ffffff",
        "--disabled": "#7a7a7a67",
        "--error": "#d34848",
        "--warning": "#d89f36",
        "--info": "#275ab9",
        "--success": "#24b43c",
        "--default": "#5f5959",
        "--credit-card": "#da3434",
        "--bank": "#2d62d4",
        "--company": "#8d33d6",
        "--category": "#2cadad",
        "--bill": "#ac9d44",
    },
    {
        title: "pastel green",
        id: "pastel",
        description: "pastel colors with green based theme",
        "--primary": "#748b91",
        "--secondary": "#c0b0b7",
        "--third": "#a89a92",
        "--background": "#f9fafa",
        "--bh": "rgb(from var(--background) calc(r - 10) calc(g - 10) calc(b - 10))",
        "--text-1": "#000000",
        "--text-2": "#888888",
        "--text-3": "#ffffff",
        "--border-color": "#748b91",
        "--disabled": "#7a7a7a67",
        "--error": "#bb3232",
        "--warning": "#b9882d",
        "--info": "#0b3d9b",
        "--success": "#248133",
        "--default": "#474141",
        "--credit-card": "#da3434",
        "--bank": "#5c84da",
        "--company": "#a369d3",
        "--category": "#44acac",
        "--bill": "#ac9d44",
    },
    {
        title: "dark grey",
        id: "dark-grey",
        description: "dark theme with grey based colors",
        "--primary": "#4b84af",
        "--secondary": "#3a2e6b",
        "--third": "#5e3a88",
        "--background": "#060b0e",
        "--bh": "#a094d133",
        "--text-1": "#d5d6f1",
        "--text-2": "#5d6199",
        "--text-3": "#000d55",
        "--border-color": "#4b84af",
        "--disabled": "#7a7a7a67",
        "--error": "#bb3232",
        "--warning": "#b9882d",
        "--info": "#0b3d9b",
        "--success": "#248133",
        "--default": "#474141",
        "--credit-card": "#da3434",
        "--bank": "#5c84da",
        "--company": "#a369d3",
        "--category": "#44acac",
        "--bill": "#ac9d44",
    },

    {
        title: "blues",
        id: "blues",
        description: "blue-themed colors",
        "--primary": "#2d315c",
        "--secondary": "#8d92d3",
        "--third": "#3943c6",
        "--background": "#efeff5",
        "--bh": "#a094d14d",
        "--text-1": "#000d55",
        "--text-2": "#3c3e5c",
        "--text-3": "#d5d6f1",
        "--border-color": "#2d315c",
        "--disabled": "#7a7a7a67",
        "--error": "#bb3232",
        "--warning": "#b9882d",
        "--info": "#0b3d9b",
        "--success": "#248133",
        "--default": "#474141",
        "--credit-card": "#da3434",
        "--bank": "#5c84da",
        "--company": "#a369d3",
        "--category": "#44acac",
        "--bill": "#ac9d44",
    },
];
